#!/bin/bash
IFS=
DECODED_MESSAGE=""
while read -r line || [[ -n "$line" ]]; do
    first_char=$(echo "$line" | cut -c 1)
    DECODED_MESSAGE+="$first_char"
done < "${1:-/dev/stdin}"
echo -e "$DECODED_MESSAGE"
